### ISSUE TITLE
Deployment Error 'Missing SubscriptionId'

### ISSUE THREAD

**Issue by Hannes1910** [RazorSPoint/azure-devops-azure-policy-extension#5]
I'm trying to deploy a Policy Definition by using the "Splitted Deployment", but receiving the following error message:
![image](https://user-images.githubusercontent.com/43246439/54451967-4ad7ea80-4754-11e9-9236-b3e1b34ce490.png)

Settings of the DevOps Task:
Definition Location: Management Group
Type of Deployment: Splitted Deployment
Mode: all
Name, Displayname, Description, Category: --> All Containing a value
Parameters / Policy Rule: --> Files are published from CI Pipeline

These are the two files I'm trying to deploy (originally JSON files - converted to txt in order to upload here):
[Policy_AuditPIP_Parameters copy.txt](https://github.com/RazorSPoint/azure-devops-azure-policy-extension/files/2972348/Policy_AuditPIP_Parameters.copy.txt)
[Policy_AuditPIP_Rule copy.txt](https://github.com/RazorSPoint/azure-devops-azure-policy-extension/files/2972349/Policy_AuditPIP_Rule.copy.txt)

A Service Connection to a Subscription within the scope of the target management group has been configured and works also (SPN Role: Resource Policy Contributor).

Any ideas if I'm doing something wrong?

**Comment by SebastianSchuetze** [comment]
Thanks! Gonna check this!

**Comment by SebastianSchuetze** [comment]
#7

**Comment by SebastianSchuetze** [comment]
@Hannes1910 issue is fixed and should work now!
